FROM node:16-alpine AS base
WORKDIR /var/server

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# RUNNER
FROM base AS production
WORKDIR /var/server

RUN npm run build

RUN ls -la

CMD ["node", "./dist/src/index.js"]